version: '3'
services:

  service:
    image: hack4law.azurecr.io/hack4law-assistant-ksef:0.1
    ports:
      - "8080:8080"
    environment:
      - AUTH_USER=hack4law
      - AUTH_PASSWORD=d95DaH34jcoP
      - KSEF_TOKEN=d4be2a49291b43f321e99d15dbf91c4ab31db20d363f6fa04e59c3adef316f0b
      - KSEF_ENVIRONMENT=test
      - KSEF_NIP=6891152920







