micronaut:
  application:
    name: hack4lawAssistantKsef
  metrics:
    export:
      azuremonitor:
        enabled: false
        instrumentationKey: ${AZUREMONITOR_INSTRUMENTATION_KEY}
        step: PT1M
    enabled: true
netty:
  default:
    allocator:
      max-order: 3

ksef:
  token:
  environment: test
  nip: 6891152920

auth:
  user: hack4law
  password: d95DaH34jcoP
